#ifndef GANON_ERR_H
#define GANON_ERR_H

typedef enum {
    /* Success */
    E__SUCCESS = 0,

    /* Generic errors */
    E__INVALID_ARG_NULL_POINTER = 0x001,

    /* main.c */
    E__MAIN__RC_DEMO__SOME_ERROR = 0x100,

    /* args.c */
    E__ARGS__NULL_POINTER = 0x200,
    E__ARGS__CONFLICTING_ARGUMENTS,
    E__ARGS__MISSING_REQUIRED_ARGUMENT,
    E__ARGS__INVALID_FORMAT,
    E__ARGS__UNKNOWN_FLAG,
    E__ARGS__CONNECT_PARSING_ERROR,
    E__ARGS__TOO_MANY_CONNECT_ENTRIES,
    E__ARGS__INVALID_NODE_ID,
    E__ARGS__INVALID_CONNECT_TIMEOUT,
    E__ARGS__INVALID_RECONNECT_RETRIES,
    E__ARGS__INVALID_RECONNECT_DELAY,

    /* network.c */
    E__NET__SOCKET_CREATE_FAILED = 0x300,
    E__NET__SOCKET_BIND_FAILED,
    E__NET__SOCKET_LISTEN_FAILED,
    E__NET__SOCKET_ACCEPT_FAILED,
    E__NET__SOCKET_CONNECT_FAILED,
    E__NET__SOCKET_SETOPT_FAILED,
    E__NET__THREAD_CREATE_FAILED,
    E__NET__INVALID_SOCKET,
    E__NET__SEND_FAILED,

    /* session.c */
    E__SESSION__HANDLE_NODE_INIT_FAILED = 0x401,
    E__SESSION__HANDLE_MESSAGE_FAILED,
    E__SESSION__CONNECTION_REJECTED,
    E__SESSION__INVALID_MESSAGE,

    /* routing.c */
    E__ROUTING__NODE_NOT_FOUND = 0x501,
    E__ROUTING__TABLE_FULL,
    E__ROUTING__INVALID_ARG,

    /* crypto (transport-layer encryption) */
    E__CRYPTO__HANDSHAKE_FAILED = 0x601,
    E__CRYPTO__DECRYPT_FAILED,
    E__CRYPTO__REPLAY_DETECTED,
} err_t;

#endif /* #ifndef GANON_ERR_H */