#ifndef GANON_ERR_H
#define GANON_ERR_H

typedef enum {
    E__GANON_MAIN_SUCCESS,
    E__GANON_MAIN_FAILURE,

    E__LOGGING_INIT_FAILURE,
    E__LOGGING_WRITE_FAILURE,

    E__CONFIG_LOAD_FAILURE,
    E__CONFIG_PARSE_FAILURE,
    E__CONFIG_MISSING_VALUE,

    E__NETWORK_INIT_FAILURE,
    E__NETWORK_CONNECT_FAILURE,
    E__NETWORK_SEND_FAILURE,
    E__NETWORK_RECV_FAILURE,

    E__MEMORY_ALLOCATION_FAILURE,
    E__MEMORY_NULL_POINTER,
} err_t;

#endif