#ifndef GANON_ERR_H
#define GANON_ERR_H

typedef enum {
    E__SUCCESS = 0,
    E__GANON_FAILURE,
    E__MAIN__RC_DEMO__SOME_ERROR,
    E__MAIN__FAILURE,
    E__ARGS__INVALID_ARGUMENTS,
    E__ARGS__CONFLICTING_ARGUMENTS,
    E__ARGS__MISSING_VALUE,
    E__ARGS__INVALID_VALUE,
    E__ARGS__INVALID_ARGUMENT,
} err_t;

#endif